name: 06 - Contexts

on:
    push:
    workflow_dispatch: 
      inputs:
        name: 
            type: boolean
            description: Defining an inputm to workflow_dispatch
            default: false

jobs:
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - name: Display Information
              run: |
                echo "Event name: ${{ github.event_name }}"
                echo "Ref: ${{ github.ref }}"
                echo "SHA: ${{ github.sha }}"
                echo "Actor: ${{ github.actor }}"
                echo "Workflow: ${{ github.workflow }}"
                echo "Run ID: ${{ github.run_id }}"
                echo "Run number: ${{ github.run_number }}"
            - name: Retrieve Variable
              run: |
                echo "Variable Name: ${{ vars.MY_VAR }}"

run-name: 06 - Contexts. Experimenting with Contexts :)