name: 17 - 1 - Custom Actions - Composite

on: 
  workflow_dispatch:
    inputs:
      target-env:
        description: Choose the environment where to execute this action
        type: choice
        options:
          - dev
          - prod
env:
  working-directory: 17-custom-actions/react-app


run-name: 17 - 1 Custom Actions - Composite | env - ${{inputs.target-env}}

jobs:
  build:
    runs-on: ubuntu-latest 
    defaults:
      run:
        working-directory: ${{env.working-directory}}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node and NPM Dependencies
        uses: ./.github/actions/composite-cache-deps
        with:
          node-version: 20.x
          working-dir: 17-custom-actions/react-app
      - name: Test
        run: npm ci

      - name: Build
        run: npm run build


